### ISSUE TITLE
Trouble Building

### ISSUE THREAD

**Issue by Jstills4960** [karlcswanson/micboard#43]
I seem to be having trouble building Micboard. 
I am following the installation instructions perfectly, but it seems to be giving a ton of errors. 

I work in the Production Ministry at a very large multi-site church and we really want to make this work.

**Comment by sethioy** [comment]
I am having a similar issue, just trying to check this out by building it in terminal. The macos server app does not want to open either. I may just try building it in Ubuntu.

**Comment by dustenharward** [comment]
I just tried building this on a RaspberryPi (Debian). This package probably needs a solid update to address a bunch of deprecated functions across both Mac and linux....

I am happy to work with someone to provide logs and errors. I did find that the mac build works on OS X version 11.1 but only this version.

**Comment by dustenharward** [comment]
Here are some details on the debian install on a Raspberry Pi 4:

Issue1: Running this: curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash - 
Gives the result: ## Your distribution, identified as "bookworm", is not currently supported, please contact NodeSource at https://github.com/nodesource/distributions/issues if you think this is incorrect or would like your distribution to be considered for support
So i try to install version 16 which is the oldest supported version and i end up being able to get to the step "npm install --only=prod" before hitting the errors of: 

pm WARN config only Use `--omit=dev` to omit dev dependencies from the install.
npm WARN deprecated source-map-url@0.4.1: See https://github.com/lydell/source-map-url#deprecated
npm WARN deprecated figgy-pudding@3.5.2: This module is no longer supported.
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated source-map-resolve@0.5.3: See https://github.com/lydell/source-map-resolve#deprecated
npm WARN deprecated chokidar@2.1.8: Chokidar 2 does not receive security updates since 2019. Upgrade to chokidar 3 with 15x fewer dependencies
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated tar@2.2.2: This version of tar is no longer supported, and will not receive security updates. Please upgrade asap.
npm WARN deprecated popper.js@1.16.1: You can find the new Popper v2 at @popperjs/core, this package is dedicated to the legacy v1
npm ERR! code 1
npm ERR! path /home/lfch/micboard/node_modules/node-sass
npm ERR! command failed
npm ERR! command sh -c -- node scripts/build.js
npm ERR! Building: /usr/bin/node /home/lfch/micboard/node_modules/node-sass/node_modules/node-gyp/bin/node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp verb cli [
npm ERR! gyp verb cli   '/usr/bin/node',
npm ERR! gyp verb cli   '/home/lfch/micboard/node_modules/node-sass/node_modules/node-gyp/bin/node-gyp.js',
npm ERR! gyp verb cli   'rebuild',
npm ERR! gyp verb cli   '--verbose',
npm ERR! gyp verb cli   '--libsass_ext=',
npm ERR! gyp verb cli   '--libsass_cflags=',
npm ERR! gyp verb cli   '--libsass_ldflags=',
npm ERR! gyp verb cli   '--libsass_library='
npm ERR! gyp verb cli ]
npm ERR! gyp info using node-gyp@3.8.0
npm ERR! gyp info using node@16.20.2 | linux | arm64
npm ERR! gyp verb command rebuild []
npm ERR! gyp verb command clean []
npm ERR! gyp verb clean removing "build" directory
npm ERR! gyp verb command configure []
npm ERR! gyp verb check python checking for Python executable "python2" in the PATH
npm ERR! gyp verb `which` failed Error: not found: python2
npm ERR! gyp verb `which` failed     at getNotFoundError (/home/lfch/micboard/node_modules/which/which.js:13:12)
npm ERR! gyp verb `which` failed     at F (/home/lfch/micboard/node_modules/which/which.js:68:19)
npm ERR! gyp verb `which` failed     at E (/home/lfch/micboard/node_modules/which/which.js:80:29)
npm ERR! gyp verb `which` failed     at /home/lfch/micboard/node_modules/which/which.js:89:16
npm ERR! gyp verb `which` failed     at /home/lfch/micboard/node_modules/isexe/index.js:42:5
npm ERR! gyp verb `which` failed     at /home/lfch/micboard/node_modules/isexe/mode.js:8:5
npm ERR! gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:202:21)
npm ERR! gyp verb `which` failed  python2 Error: not found: python2
npm ERR! gyp verb `which` failed     at getNotFoundError (/home/lfch/micboard/node_modules/which/which.js:13:12)
npm ERR! gyp verb `which` failed     at F (/home/lfch/micboard/node_modules/which/which.js:68:19)
npm ERR! gyp verb `which` failed     at E (/home/lfch/micboard/node_modules/which/which.js:80:29)
npm ERR! gyp verb `which` failed     at /home/lfch/micboard/node_modules/which/which.js:89:16
npm ERR! gyp verb `which` failed     at /home/lfch/micboard/node_modules/isexe/index.js:42:5
npm ERR! gyp verb `which` failed     at /home/lfch/micboard/node_modules/isexe/mode.js:8:5
npm ERR! gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:202:21) {
npm ERR! gyp verb `which` failed   code: 'ENOENT'
npm ERR! gyp verb `which` failed }
npm ERR! gyp verb check python checking for Python executable "python" in the PATH
npm ERR! gyp verb `which` succeeded python /usr/bin/python
npm ERR! gyp ERR! configure error 
npm ERR! gyp ERR! stack Error: Command failed: /usr/bin/python -c import sys; print "%s.%s.%s" % sys.version_info[:3];
npm ERR! gyp ERR! stack   File "<string>", line 1
npm ERR! gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
npm ERR! gyp ERR! stack                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
npm ERR! gyp ERR! stack SyntaxError: Missing parentheses in call to 'print'. Did you mean print(...)?
npm ERR! gyp ERR! stack 
npm ERR! gyp ERR! stack     at ChildProcess.exithandler (node:child_process:402:12)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
npm ERR! gyp ERR! stack     at maybeClose (node:internal/child_process:1100:16)
npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:304:5)
npm ERR! gyp ERR! System Linux 6.1.0-rpi8-rpi-v8
npm ERR! gyp ERR! command "/usr/bin/node" "/home/lfch/micboard/node_modules/node-sass/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
npm ERR! gyp ERR! cwd /home/lfch/micboard/node_modules/node-sass
npm ERR! gyp ERR! node -v v16.20.2
npm ERR! gyp ERR! node-gyp -v v3.8.0
npm ERR! gyp ERR! not ok 
npm ERR! Build failed with error code: 1

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2024-02-11T17_06_20_090Z-debug-0.log
and i am not able to move forward from here.

**Comment by stuart-adams** [comment]
@dustenharward 

I've tried this project multiple times and I was about to take another stab at it. 

But since the last try, ChatGPT has taken over all of my software debugging. I plugged your entire post into a thread, and this is what it spit out. 


"It looks like you’re encountering several issues related to deprecated packages and Python version mismatches during the installation of dependencies for your Node.js project on Debian Bookworm (Raspberry Pi 4).

Here’s how you can address these issues:

	1.	NodeSource Not Supporting “Bookworm”:
Since Node.js v10 is no longer supported for your current Debian version, you can continue with Node.js v16 or v18, which are stable releases. You already moved to Node.js v16, so that’s good.
	2.	Python2 Not Found:
Node-sass is trying to use Python 2, which is no longer supported. The error python2: not found indicates that it’s looking for Python 2 specifically. You should install Python 3 and update the configuration for node-gyp to use Python 3 instead of Python 2:
	•	Install Python 3:

sudo apt install python3
sudo ln -s /usr/bin/python3 /usr/bin/python


	•	Ensure that node-gyp uses Python 3:

npm config set python /usr/bin/python3


	3.	Node-sass Dependency Issues:
node-sass has been deprecated and replaced by dart-sass or sass. You can avoid further issues by migrating from node-sass:
	•	Install sass instead:

npm uninstall node-sass
npm install sass


	4.	Handling Deprecated Libraries:
Many libraries like request, chokidar, and uuid are deprecated. You can try to update the dependencies in your project:
	•	Try running this to update all dependencies:

npm outdated
npm update


If the npm update command doesn’t resolve all deprecations, you might need to manually update specific packages by checking the project’s package.json file.

	5.	Rebuilding Node-Gyp:
If the build still fails after addressing Python and node-sass, try cleaning the npm cache and rebuilding:

npm cache clean --force
npm rebuild


	6.	Potential Issue with Node-Gyp and ARM64 Architecture:
Since you’re on an ARM64 architecture, ensure that all required build tools are installed:

sudo apt-get install build-essential
sudo apt-get install gcc g++ make



Summary Steps:

	1.	Ensure Python 3 is installed and properly configured for node-gyp.
	2.	Replace deprecated node-sass with sass.
	3.	Update all outdated or deprecated libraries.
	4.	Clean and rebuild the npm cache.

After these steps, you should be able to move past the errors. Let me know if any issues persist!"

I'm going to try this myself.

**Comment by wjarrell-ccc** [comment]
The project can no longer be built on modern operating systems with the original codebase. I've created a maintained fork at https://github.com/wjarrell-ccc/micboard that modernizes the codebase for Ubuntu 22.04/24.04 LTS, Node.js 20, and webpack 5. Updated installation docs are included. A pull request has been submitted to this repo if Karl ever returns. I'm working on Pi and MacOS this week
